### ISSUE TITLE
Language selection in footer

### ISSUE THREAD

**Issue by Esclaire** [nthiebes/booky.io#43]
This issue is about the design of the language selection in the footer.

**Comment by Esclaire** [comment]
<img width="947" alt="bildschirmfoto 2019-02-15 um 15 59 57" src="https://user-images.githubusercontent.com/17746845/52864811-4ad7d100-313b-11e9-932f-be8995a7748f.png">

**Comment by Esclaire** [comment]
If you'd consider this as a possible idea for a "nicer" dropdown, I just checked the mark-up and found something very interesting about it:

A click event listens on Deutschland and the flag img, the elements container got: 
`aria-haspopup="listbox"` `and aria-expanded="false"` as attributes.

On click, the aria-expandet changes to true, and the ul with all the other languages also has the `aria-haspopup="listbox"` which creates the connection between the original selection and the pop-up. 
This is a valid case of how to use those aria attributes according to: https://www.w3.org/TR/wai-aria/#aria-haspopup and will give us the chance to create a pretty dropdown without the cost of a11y.

**Comment by nthiebes** [comment]
<img width="337" alt="bildschirmfoto 2019-02-17 um 10 07 56" src="https://user-images.githubusercontent.com/7579238/52910720-eed88e00-329b-11e9-8cb9-a9fcbe898787.png">
I added them directly without dropdown.
