### ISSUE TITLE
Web server is down

### ISSUE THREAD

**Issue by hyjwonder** [nthiebes/booky.io#455]
Is the [booky.io site](https://booky.io/) down? When I open it, the page says "Web server is down. Error code 521." Can you bring it back online?

**Comment by nthiebes** [comment]
Hello, this was a planned downtime by our hosting provider doing some maintenance on our server. booky is back online again :).

**Comment by nthiebes** [comment]
Oh, and make sure to follow us on Twitter to stay informed about future maintenance: https://twitter.com/booky_io
